swagger: '2.0'
info:
  version: 0.0.2
  title: 1-13 商品模块
paths:
  /goods:
    post:
      tags:
      - goods
      summary: 商家新建商品
      description: 新增商品SPU（ID自动生成，ShopID自动关联，状态未上架，规格为空）
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: body
        name: good_spu
        description: 商品SPU
        required: true
        schema:
          properties:
            name:
              type: string
            brand_id:
              type: integer
            category_id:
              type: integer
            freight_id:
              type: integer
            goods_sn:
              type: string
            description:
              type: string
            image_url:
              type: string
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/goods_spu'
        902:
          description: 提交的属性不合法
    get:
      tags:
      - goods
      summary: 用户获取商品列表
      description: 查询已上架商品列表
      parameters:
      - in: query
        name: page
        type: integer
        description: 页数
      - in: query
        name: pageSize
        type: integer
        description: 每页数量
      - in: query
        name: sort
        type: string
        enum:
        - price_ascending
        - price_descending
        - comments
        description: 排列
      - in: query
        name: search
        type: string
        description: 搜索关键字
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                brand_id:
                  type: integer
                category_id:
                  type: integer
                goods_sn:
                  type: string
                description:
                  type: string
                image_url:
                  type: string
                spec:
                  type: array
                  items:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      original_price:
                        type: number
                      configuration:
                        type: object
                      weight:
                        type: number
                      image_url:
                        type: string
                      inventory:
                        type: integer
                      description:
                        type: string
        902:
          description: 查询条件错误
  /goods/{spu_id}:
    put:
      tags:
      - goods
      summary: 商家修改商品SPU
      description: 店铺管理员修改商品信息
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      - in: body
        name: good_spu
        description: 商品SPU
        required: true
        schema:
          properties:
            name:
              type: string
            freight_id:
              type: integer
            goods_sn:
              type: string
            description:
              type: string
            image_url:
              type: string
      responses:
        200:
          description: OK
        901:
          description: 无权操作商品
        904:
          description: 商品正在使用
    get:
      tags:
      - goods
      summary: 用户查看商品信息
      description: 查看已上架商品详情
      parameters:
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      responses:
        200:
          description: OK
          schema:
            properties:
              name:
                type: string
              brand_id:
                type: integer
              category_id:
                type: integer
              goods_sn:
                type: string
              description:
                type: string
              image_url:
                type: string
              spec:
                type: array
                items:
                  properties:
                    name:
                      type: string
                    original_price:
                      type: number
                    configuration:
                      type: object
                    weight:
                      type: number
                    image_url:
                      type: string
                    inventory:
                      type: integer
                    description:
                      type: string
    delete:
      tags:
      - goods
      summary: 商家逻辑删除商品SPU
      description: 店铺管理员删除商品
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      responses:
        200:
          description: OK
        901:
          description: 无权操作商品
    
  /goods/{spu_id}/onshelf:
    put:
      tags:
      - goods
      summary: 商家上架商品
      description: 店铺管理员上架商品
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      responses:
        200:
          description: OK
        901:
          description: 无权操作商品
    delete:
      tags:
      - goods
      summary: 商家下架商品
      description: 店铺管理员下架商品
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      responses:
        200:
          description: OK
        901:
          description: 无权操作商品

  /goods/{spu_id}/spec:
    post:
      tags:
      - goods
      summary: 商家新建商品规格
      description: 店铺管理员新增商品规格（ID和序号自动生成，SPUID自动关联）
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      - in: body
        name: goods_sku
        description: 商品SKU
        required: true
        schema:
          properties:
            name:
              type: string
            original_price:
              type: number
            configuration:
              type: object
            weight:
              type: number
            image_url:
              type: number
            inventory:
              type: integer
            description:
              type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/goods_sku'
        901:
          description: 无权操作商品SPU
        902:
          description: 提交的属性不合法
  /goods/{spu_id}/spce/{sku_id}:
    put:
      tags:
      - goods
      summary: 商家修改商品规格
      description: 店铺管理员修改商品规格信息
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      - in: path
        name: sku_id
        type: integer
        description: 商品SKU ID
        required: true
      - in: body
        name: goods_sku
        description: 商品SKU
        required: true
        schema:
          properties:
            name:
              type: string
            original_price:
              type: number
            configuration:
              type: object
            weight:
              type: number
            image_url:
              type: number
            inventory:
              type: integer
            description:
              type: string
      responses:
        200:
          description: OK
        902:
          description: 提交的属性不合法
    delete:
      tags:
      - goods
      summary: 商家逻辑删除商品规格
      description: 店铺管理员移除可用的商品规格
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      - in: path
        name: sku_id
        type: integer
        description: 商品SKU ID
        required: true
      responses:
        200:
          description: OK
        901:
          description: 无权操作商品

  /goods/{spu_id}/spec/{sku_id}/floating_price:
    post:
      tags:
      - goods
      summary: 商家新增规格浮动价格
      description: 店铺管理员新增商品规格价格浮动
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      - in: path
        name: sku_id
        type: integer
        description: 商品SKU ID
        required: true
      - in: body
        name: floating_price
        required: true
        schema:
          properties:
            activity_price:
              type: number
            begin_time:
              type: string
            end_time:
              type: string
            quantity:
              type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/floating_price'
        901:
          description: 无权操作商品
        902:
          description: 提交的属性不合法
    delete:
      tags:
      - goods
      summary: 商家取消浮动价格
      description: 逻辑删除商品规格价格浮动
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      - in: path
        name: spu_id
        type: integer
        description: 商品SPU ID
        required: true
      - in: path
        name: sku_id
        type: integer
        description: 商品SKU ID
        required: true
      responses:
        200:
          description: OK
        901:
          description: 无权操作商品
  /shop/{shop_id}/goods:
    get:
      tags:
      - goods
      summary: 用户查看店铺商品
      description: 用户查看店铺内上架的商品
      parameters:
      - in: path
        name: shop_id
        type: integer
        description: 店铺ID
        required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                brand_id:
                  type: integer
                category_id:
                  type: integer
                goods_sn:
                  type: string
                description:
                  type: string
                image_url:
                  type: string
                spec:
                  type: array
                  items:
                    properties:
                      name:
                        type: string
                      original_price:
                        type: number
                      configuration:
                        type: object
                      weight:
                        type: number
                      image_url:
                        type: string
                      inventory:
                        type: integer
                      description:
                        type: string
  /shop/:my/goods:
    get:
      tags:
      - goods
      summary: 商家获得店铺内商品
      description: 店铺管理员查看店铺内所有商品（包含未上架商品）
      parameters:
      - in: header
        name: authorization
        type: string
        description: Token
        required: true
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/goods_spu'
definitions:
  goods_spu:
    properties:
      id:
        type: integer
      name:
        type: string
      brand_id:
        type: integer
      category_id:
        type: integer
      freight_id:
        type: integer
      shop_id:
        type: integer
      goods_sn:
        type: string
      description:
        type: string
      image_url:
        type: string
      state:
        type: string
      spec:
        type: array
        items:
          $ref: '#/definitions/goods_sku'
      be_deleted:
        type: boolean
  goods_sku:
    properties:
      id:
        type: integer
      goods_spu_id:
        type: integer
      sku_sn:
        type: integer
      name:
        type: string
      original_price:
        type: number
      configuration:
        type: object
      weight:
        type: number
      image_url:
        type: string
      inventory:
        type: integer
      description:
        type: string
      be_deleted:
        type: boolean
  floating_price:
    properties:
      id:
        type: integer
      goods_sku_id:
        type: integer
      activity_price:
        type: number
      begin_time:
        type: string
      end_time:
        type: string
      quantity:
        type: integer
      created_by:
        type: integer
      modified_by:
        type: integer
