swagger: "2.0"
info:
  version: "0.0.1"
  title: "1-13 商品相关模块API"
tags:
- name: "goods"
  description: "商品模块"
- name: "category"
  description: "品类模块"
schemes:
- "http"
paths:
  /goods:
    get:
      tags:
      - "goods"
      summary: "获取商品列表"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "search"
        type : "string"
        description: "关键词"
      - in: "query"
        name: "price"
        type : "string"
        # example: "100-150"
        description: "价格区间"
      - name: "sort"
        in: "query"
        type: "string"
        default: comprehensive
        enum:
        - comprehensive
        - sales
        - comment
        - price_descending
        - price_ascending
        - latest
        description: "排序"
      - name: "page"
        in: "query"
        description: "页码"
        type: "integer"
        default: 1
      - name: "pageSize"
        in: "query"
        description: "每页数目"
        type: "integer"
        default: 30
      - name: "special"
        in: "query"
        type: "string"
        description: "特殊商品"
        enum:
        - presale
        - groupon
        - hot
      - name: "brand"
        in: "query"
        type: "string"
        description: "品牌ID"
      - name: "category"
        in: "query"
        type: "string"
        description: "品类ID"
      responses:
        default:
          description: "商品列表"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  $ref: "#/definitions/GoodsPreview"
    post:
      tags:
      - "goods"
      summary: "新增商品"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "header"
        name: "authorization"
        type: "string"
        required: true
        description: "用户Token"
      - in: "body"
        required: true
        name: "body"
        schema:
          $ref: "#/definitions/GoodsEditable"
      responses:
        "922":
          description: "属性不合法"
        "923":
          description: "权限错误"
        default:
          description: "商品详情"
          schema:
            $ref: "#/definitions/GoodsDetailed"
          
  /goods/{id}:
    get:
      tags:
      - "goods"
      summary: "查询商品详情"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "integer"
        required: true
        description: "商品ID"
      - in: "query"
        name: "time"
        type: "string"
        description: "历史版本"
      responses:
        default:
          description: "商品详情"
          schema:
            $ref: "#/definitions/GoodsDetailed"
    put:
      tags:
      - "goods"
      summary: "修改商品"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "integer"
        required: true
        description: "商品ID"
      - in: "header"
        name: "authorization"
        type: "string"
        required: true
        description: "用户Token"
      - in: "body"
        required: true
        name: "body"
        schema:
          $ref: "#/definitions/GoodsEditable"
      responses:
        "923":
          description: "ID不存在"
        "924":
          description: "属性不合法"
        "925":
          description: "权限错误"
        default:
          description: "操作结果"
          schema:
            $ref: "#/definitions/GoodsDetailed"
    delete:
      tags:
      - "goods"
      summary: "删除商品"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "integer"
        required: true
        description: "商品ID"
      - in: "header"
        name: "authorization"
        type: "string"
        required: true
        description: "用户Token"
      responses:
        "925":
          description: "ID不存在"
        "923":
          description: "权限错误"
        default:
          description: "商品详情"
          schema:
            type: "object"
            properties:
              errNo:
                type: "integer"
              errMsg: 
                type: "string"
  /category:
    get:
      tags:
      - "category"
      summary: "获取品类列表"
      produces:
      - "application/json"
      responses:
        "default":
          description: "品类列表"
          schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  properties:
                    id:
                      type: "integer"
                      format: "int64"
                    name:
                      type: "string"
                    logoUrl:
                      type: "string"
                    description:
                      type: "string"
                    
    post:
      tags:
      - "category"
      summary: "新增品类"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "authorization"
        description: "用户 Token"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
           properties:
            name:
              type: "string"
            logoUrl:
              type: "string"
            description:
              type: "string"
      responses:
        "905":
          description: "品类已存在"
        "906":
          description: "属性不合法"
        "default":
          description: "品类详情"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
              logoUrl:
                type: "string"
              description:
                type: "string"
  /category/{id}:
    put:
      tags:
      - "category"
      summary: "修改品类信息"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "authorization"
        description: "用户Token"
        required: true
        type: "string"
      - in: "path"
        name: "id"
        description: "品牌ID"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          properties:
            name:
              type: "string"
            logoUrl:
              type: "string"
            description:
              type: "string"
      responses:
        "907":
          description: "ID不存在"
        "902":
          description: "属性不合法"
        "default":
          description: "品类详情"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
              logoUrl:
                type: "string"
              description:
                type: "string"
    delete:
      tags:
      - "category"
      summary: "删除品类"
      produces:
      - "application/json"
      parameters:
      - name: "authorization"
        type: "string"
        in: "header"
        description: "用户Token"
        required: true
      - name: "id"
        in: "path"
        description: "品牌ID"
        required: true
        type: "string"
      responses:
        "default":
          description: "成功"
          schema:
            type: "object"
            properties:
              errNo:
                type: "integer"
              errMsg: 
                type: "string"
        "912":
          description: "ID不存在"
definitions:
  GoodsPreview:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      price:
        type: "number"
      commentNumber:
        type: "integer"
      pictureUrl:
        type: "string"
      store:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          name:
            type: "string"
  GoodsDetailed:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      price:
        type: "number"
      pictureUrl:
        type: "string"
      description:
        type: "string"
      stock:
        type: "integer"
      onShelf:
        type: "boolean"
      weight:
        type: "number"
      volume:
        type: "number"
      categories:
        type: "array"
        items:
          properties:
            id:
              type: "integer"
              format: "int64"
            name:
              type: "string"
      brands:
        type: "array"
        items:
          properties:
            id:
              type: "integer"
              format: "int64"
            name:
              type: "string"
      store:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          name:
            type: "string"
      commentNumber:
        type: "integer"
      spType:
        type: "string"
      spBeginTime:
        type: "string"
      spEndTime:
        type: "string"
      spPrice:
        type: "string"
      preFinalBegin:
        type: "string"
      preFinalEnd:
        type: "string"
      hotLimit:
        type: "integer"
      groupRule:
        type: "string"
  GoodsEditable:
    type: "object"
    properties:
      name:
        type: "string"
      price:
        type: "number"
      stock:
        type: "integer"
      pictureUrl:
        type: "string"
      description:
        type: "string"
      onShelf:
        type: "boolean"
      weight:
        type: "number"
      volume:
        type: "number"
      brands:
        type: "array"
        items:
          properties:
            id:
              type: "integer"
              format: "int64"
      categories:
        type: "array"
        items:
          properties:
            id:
              type: "integer"
              format: "int64"
      spType:
        type: "string"
      spBeginTime:
        type: "string"
      spEndTime:
        type: "string"
      spPrice:
        type: "string"
      preFinalBegin:
        type: "string"
      preFinalEnd:
        type: "string"
      hotLimit:
        type: "integer"
      groupRule:
        type: "string"
